# DO NOT DELETE

sampleIM.o: /usr/include/stdio.h /usr/include/_ansi.h /usr/include/newlib.h
sampleIM.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
sampleIM.o: /usr/include/cygwin/config.h
sampleIM.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
sampleIM.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
sampleIM.o: /usr/include/sys/reent.h /usr/include/sys/_types.h
sampleIM.o: /usr/include/sys/lock.h /usr/include/sys/types.h
sampleIM.o: /usr/include/machine/types.h /usr/include/sys/features.h
sampleIM.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
sampleIM.o: /usr/include/stdint.h /usr/include/sys/stdio.h
sampleIM.o: /usr/include/locale.h /usr/X11R6/include/X11/Xlib.h
sampleIM.o: /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h
sampleIM.o: /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h
sampleIM.o: /usr/X11R6/include/X11/keysym.h
sampleIM.o: /usr/X11R6/include/X11/keysymdef.h IMdkit/IMdkit.h
sampleIM.o: /usr/X11R6/include/X11/Xmd.h IMdkit/Xi18n.h IMdkit/XimProto.h
sampleIM.o: /usr/include/stdlib.h /usr/include/machine/stdlib.h
sampleIM.o: /usr/include/alloca.h winIC.h
winIC.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
winIC.o: /usr/include/_ansi.h /usr/include/newlib.h /usr/include/sys/config.h
winIC.o: /usr/include/machine/ieeefp.h /usr/include/cygwin/config.h
winIC.o: /usr/include/sys/_types.h /usr/include/sys/lock.h
winIC.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
winIC.o: /usr/include/machine/types.h /usr/include/sys/features.h
winIC.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
winIC.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
winIC.o: /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xosdefs.h
winIC.o: /usr/X11R6/include/X11/Xos.h /usr/include/string.h
winIC.o: /usr/include/sys/reent.h /usr/include/fcntl.h
winIC.o: /usr/include/sys/fcntl.h /usr/include/sys/stat.h /usr/include/time.h
winIC.o: /usr/include/machine/time.h /usr/include/signal.h
winIC.o: /usr/include/sys/signal.h /usr/include/cygwin/signal.h
winIC.o: /usr/include/cygwin/stat.h /usr/include/unistd.h
winIC.o: /usr/include/sys/unistd.h /usr/include/getopt.h
winIC.o: /usr/include/sys/time.h /usr/include/sys/select.h
winIC.o: /usr/include/sys/cdefs.h /usr/X11R6/include/X11/Xarch.h
winIC.o: IMdkit/IMdkit.h /usr/X11R6/include/X11/Xmd.h IMdkit/Xi18n.h
winIC.o: IMdkit/XimProto.h /usr/include/stdlib.h
winIC.o: /usr/include/machine/stdlib.h /usr/include/alloca.h IMdkit/IMdkit.h
winIC.o: winIC.h
