# DO NOT DELETE

FrameMgr.o: /usr/X11R6/include/X11/Xlibint.h /usr/X11R6/include/X11/Xlib.h
FrameMgr.o: /usr/include/sys/types.h /usr/include/_ansi.h
FrameMgr.o: /usr/include/newlib.h /usr/include/sys/config.h
FrameMgr.o: /usr/include/machine/ieeefp.h /usr/include/cygwin/config.h
FrameMgr.o: /usr/include/sys/_types.h /usr/include/sys/lock.h
FrameMgr.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
FrameMgr.o: /usr/include/machine/types.h /usr/include/sys/features.h
FrameMgr.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
FrameMgr.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
FrameMgr.o: /usr/X11R6/include/X11/Xfuncproto.h
FrameMgr.o: /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xproto.h
FrameMgr.o: /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xprotostr.h
FrameMgr.o: /usr/include/errno.h /usr/include/sys/errno.h
FrameMgr.o: /usr/include/sys/reent.h /usr/X11R6/include/X11/Xfuncs.h
FrameMgr.o: /usr/include/string.h /usr/include/stdlib.h
FrameMgr.o: /usr/include/machine/stdlib.h /usr/include/alloca.h FrameMgr.h
FrameMgr.o: /usr/include/stdio.h
FrameMgr.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
FrameMgr.o: /usr/include/sys/stdio.h
IMValues.o: /usr/include/stdlib.h /usr/include/_ansi.h /usr/include/newlib.h
IMValues.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
IMValues.o: /usr/include/cygwin/config.h
IMValues.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
IMValues.o: /usr/include/sys/reent.h /usr/include/sys/_types.h
IMValues.o: /usr/include/sys/lock.h /usr/include/machine/stdlib.h
IMValues.o: /usr/include/alloca.h /usr/X11R6/include/X11/Xlib.h
IMValues.o: /usr/include/sys/types.h /usr/include/machine/types.h
IMValues.o: /usr/include/sys/features.h /usr/include/cygwin/types.h
IMValues.o: /usr/include/sys/sysmacros.h /usr/include/stdint.h
IMValues.o: /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h
IMValues.o: /usr/X11R6/include/X11/Xosdefs.h IMdkit.h
IMValues.o: /usr/X11R6/include/X11/Xmd.h
IMValues.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nIMProto.o: FrameMgr.h /usr/X11R6/include/X11/Xmd.h
i18nIMProto.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nIMProto.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nIMProto.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nIMProto.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nIMProto.o: /usr/include/sys/lock.h
i18nIMProto.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nIMProto.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nIMProto.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nIMProto.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nIMProto.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nIMProto.o: /usr/X11R6/include/X11/Xosdefs.h /usr/include/stdio.h
i18nIMProto.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nIMProto.o: /usr/include/sys/reent.h /usr/include/sys/stdio.h
i18nPtHdr.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nPtHdr.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nPtHdr.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nPtHdr.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nPtHdr.o: /usr/include/sys/lock.h
i18nPtHdr.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nPtHdr.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nPtHdr.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nPtHdr.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nPtHdr.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nPtHdr.o: /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xproto.h
i18nPtHdr.o: /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xprotostr.h
i18nPtHdr.o: /usr/include/stdlib.h /usr/include/sys/reent.h
i18nPtHdr.o: /usr/include/machine/stdlib.h /usr/include/alloca.h
i18nPtHdr.o: /usr/include/string.h FrameMgr.h /usr/include/stdio.h
i18nPtHdr.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nPtHdr.o: /usr/include/sys/stdio.h IMdkit.h Xi18n.h XimProto.h XimFunc.h
i18nX.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nX.o: /usr/include/_ansi.h /usr/include/newlib.h /usr/include/sys/config.h
i18nX.o: /usr/include/machine/ieeefp.h /usr/include/cygwin/config.h
i18nX.o: /usr/include/sys/_types.h /usr/include/sys/lock.h
i18nX.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nX.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nX.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nX.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nX.o: /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xosdefs.h
i18nX.o: /usr/X11R6/include/X11/Xatom.h /usr/include/stdlib.h
i18nX.o: /usr/include/sys/reent.h /usr/include/machine/stdlib.h
i18nX.o: /usr/include/alloca.h Xtrans.h /usr/X11R6/include/X11/Xos.h
i18nX.o: /usr/include/string.h /usr/include/fcntl.h /usr/include/sys/fcntl.h
i18nX.o: /usr/include/sys/stat.h /usr/include/time.h
i18nX.o: /usr/include/machine/time.h /usr/include/signal.h
i18nX.o: /usr/include/sys/signal.h /usr/include/cygwin/signal.h
i18nX.o: /usr/include/cygwin/stat.h /usr/include/unistd.h
i18nX.o: /usr/include/sys/unistd.h /usr/include/getopt.h
i18nX.o: /usr/include/sys/time.h /usr/include/sys/select.h
i18nX.o: /usr/include/sys/cdefs.h /usr/X11R6/include/X11/Xarch.h
i18nX.o: /usr/include/sys/socket.h /usr/include/features.h
i18nX.o: /usr/include/cygwin/socket.h /usr/include/asm/socket.h
i18nX.o: /usr/include/cygwin/if.h /usr/include/cygwin/sockios.h
i18nX.o: /usr/include/cygwin/uio.h /usr/include/sys/uio.h FrameMgr.h
i18nX.o: /usr/X11R6/include/X11/Xmd.h /usr/include/stdio.h
i18nX.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nX.o: /usr/include/sys/stdio.h IMdkit.h Xi18n.h XimProto.h Xi18nX.h
i18nX.o: XimFunc.h
IMConn.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
IMConn.o: /usr/include/_ansi.h /usr/include/newlib.h
IMConn.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
IMConn.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
IMConn.o: /usr/include/sys/lock.h
IMConn.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
IMConn.o: /usr/include/machine/types.h /usr/include/sys/features.h
IMConn.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
IMConn.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
IMConn.o: /usr/X11R6/include/X11/Xfuncproto.h
IMConn.o: /usr/X11R6/include/X11/Xosdefs.h /usr/include/malloc.h
IMConn.o: /usr/include/sys/reent.h /usr/include/machine/malloc.h
IMConn.o: /usr/include/string.h IMdkit.h /usr/X11R6/include/X11/Xmd.h
IMConn.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nAttr.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nAttr.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nAttr.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nAttr.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nAttr.o: /usr/include/sys/lock.h
i18nAttr.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nAttr.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nAttr.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nAttr.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nAttr.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nAttr.o: /usr/X11R6/include/X11/Xosdefs.h
i18nAttr.o: /usr/X11R6/include/X11/Xresource.h IMdkit.h
i18nAttr.o: /usr/X11R6/include/X11/Xmd.h Xi18n.h XimProto.h
i18nAttr.o: /usr/include/stdlib.h /usr/include/sys/reent.h
i18nAttr.o: /usr/include/machine/stdlib.h /usr/include/alloca.h XimFunc.h
i18nIc.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nIc.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nIc.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nIc.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nIc.o: /usr/include/sys/lock.h
i18nIc.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nIc.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nIc.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nIc.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nIc.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nIc.o: /usr/X11R6/include/X11/Xosdefs.h IMdkit.h
i18nIc.o: /usr/X11R6/include/X11/Xmd.h Xi18n.h XimProto.h
i18nIc.o: /usr/include/stdlib.h /usr/include/sys/reent.h
i18nIc.o: /usr/include/machine/stdlib.h /usr/include/alloca.h FrameMgr.h
i18nIc.o: /usr/include/stdio.h
i18nIc.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nIc.o: /usr/include/sys/stdio.h XimFunc.h
IMMethod.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
IMMethod.o: /usr/include/_ansi.h /usr/include/newlib.h
IMMethod.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
IMMethod.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
IMMethod.o: /usr/include/sys/lock.h
IMMethod.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
IMMethod.o: /usr/include/machine/types.h /usr/include/sys/features.h
IMMethod.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
IMMethod.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
IMMethod.o: /usr/X11R6/include/X11/Xfuncproto.h
IMMethod.o: /usr/X11R6/include/X11/Xosdefs.h IMdkit.h
IMMethod.o: /usr/X11R6/include/X11/Xmd.h
i18nClbk.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nClbk.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nClbk.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nClbk.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nClbk.o: /usr/include/sys/lock.h
i18nClbk.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nClbk.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nClbk.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nClbk.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nClbk.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nClbk.o: /usr/X11R6/include/X11/Xosdefs.h IMdkit.h
i18nClbk.o: /usr/X11R6/include/X11/Xmd.h Xi18n.h XimProto.h
i18nClbk.o: /usr/include/stdlib.h /usr/include/sys/reent.h
i18nClbk.o: /usr/include/machine/stdlib.h /usr/include/alloca.h FrameMgr.h
i18nClbk.o: /usr/include/stdio.h
i18nClbk.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nClbk.o: /usr/include/sys/stdio.h XimFunc.h
i18nMethod.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nMethod.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nMethod.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nMethod.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nMethod.o: /usr/include/sys/lock.h
i18nMethod.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nMethod.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nMethod.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nMethod.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nMethod.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nMethod.o: /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xatom.h
i18nMethod.o: /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h
i18nMethod.o: /usr/X11R6/include/X11/Xprotostr.h /usr/include/stdlib.h
i18nMethod.o: /usr/include/sys/reent.h /usr/include/machine/stdlib.h
i18nMethod.o: /usr/include/alloca.h Xtrans.h /usr/X11R6/include/X11/Xos.h
i18nMethod.o: /usr/include/string.h /usr/include/fcntl.h
i18nMethod.o: /usr/include/sys/fcntl.h /usr/include/sys/stat.h
i18nMethod.o: /usr/include/time.h /usr/include/machine/time.h
i18nMethod.o: /usr/include/signal.h /usr/include/sys/signal.h
i18nMethod.o: /usr/include/cygwin/signal.h /usr/include/cygwin/stat.h
i18nMethod.o: /usr/include/unistd.h /usr/include/sys/unistd.h
i18nMethod.o: /usr/include/getopt.h /usr/include/sys/time.h
i18nMethod.o: /usr/include/sys/select.h /usr/include/sys/cdefs.h
i18nMethod.o: /usr/X11R6/include/X11/Xarch.h /usr/include/sys/socket.h
i18nMethod.o: /usr/include/features.h /usr/include/cygwin/socket.h
i18nMethod.o: /usr/include/asm/socket.h /usr/include/cygwin/if.h
i18nMethod.o: /usr/include/cygwin/sockios.h /usr/include/cygwin/uio.h
i18nMethod.o: /usr/include/sys/uio.h FrameMgr.h /usr/include/stdio.h
i18nMethod.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nMethod.o: /usr/include/sys/stdio.h IMdkit.h Xi18n.h XimProto.h XimFunc.h
i18nTr.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nTr.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nTr.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nTr.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nTr.o: /usr/include/sys/lock.h
i18nTr.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nTr.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nTr.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nTr.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nTr.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nTr.o: /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xlibint.h
i18nTr.o: /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xmd.h
i18nTr.o: /usr/X11R6/include/X11/Xprotostr.h /usr/include/errno.h
i18nTr.o: /usr/include/sys/errno.h /usr/include/sys/reent.h
i18nTr.o: /usr/X11R6/include/X11/Xfuncs.h /usr/include/string.h
i18nTr.o: /usr/include/stdlib.h /usr/include/machine/stdlib.h
i18nTr.o: /usr/include/alloca.h /usr/include/stdio.h
i18nTr.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nTr.o: /usr/include/sys/stdio.h Xtrans.h /usr/X11R6/include/X11/Xos.h
i18nTr.o: /usr/include/fcntl.h /usr/include/sys/fcntl.h
i18nTr.o: /usr/include/sys/stat.h /usr/include/time.h
i18nTr.o: /usr/include/machine/time.h /usr/include/signal.h
i18nTr.o: /usr/include/sys/signal.h /usr/include/cygwin/signal.h
i18nTr.o: /usr/include/cygwin/stat.h /usr/include/unistd.h
i18nTr.o: /usr/include/sys/unistd.h /usr/include/getopt.h
i18nTr.o: /usr/include/sys/time.h /usr/include/sys/select.h
i18nTr.o: /usr/include/sys/cdefs.h /usr/X11R6/include/X11/Xarch.h
i18nTr.o: /usr/include/sys/socket.h /usr/include/features.h
i18nTr.o: /usr/include/cygwin/socket.h /usr/include/asm/socket.h
i18nTr.o: /usr/include/cygwin/if.h /usr/include/cygwin/sockios.h
i18nTr.o: /usr/include/cygwin/uio.h /usr/include/sys/uio.h FrameMgr.h
i18nTr.o: IMdkit.h Xi18n.h XimProto.h Xi18nTr.h
i18nUtil.o: /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h
i18nUtil.o: /usr/include/_ansi.h /usr/include/newlib.h
i18nUtil.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
i18nUtil.o: /usr/include/cygwin/config.h /usr/include/sys/_types.h
i18nUtil.o: /usr/include/sys/lock.h
i18nUtil.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stddef.h
i18nUtil.o: /usr/include/machine/types.h /usr/include/sys/features.h
i18nUtil.o: /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h
i18nUtil.o: /usr/include/stdint.h /usr/X11R6/include/X11/X.h
i18nUtil.o: /usr/X11R6/include/X11/Xfuncproto.h
i18nUtil.o: /usr/X11R6/include/X11/Xosdefs.h IMdkit.h
i18nUtil.o: /usr/X11R6/include/X11/Xmd.h Xi18n.h XimProto.h
i18nUtil.o: /usr/include/stdlib.h /usr/include/sys/reent.h
i18nUtil.o: /usr/include/machine/stdlib.h /usr/include/alloca.h FrameMgr.h
i18nUtil.o: /usr/include/stdio.h
i18nUtil.o: /usr/lib/gcc-lib/i686-pc-cygwin/3.3.3/include/stdarg.h
i18nUtil.o: /usr/include/sys/stdio.h XimFunc.h
